name: Deploy to Kubernetes

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t brajeshdockerhub/insurance-api:latest ./phase2-ci-cd-docker
        docker push brajeshdockerhub/insurance-api:latest

    - name: Decode kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./phase4-Kubernetes-Monitoring/deployment.yaml
        kubectl apply -f ./phase4-Kubernetes-Monitoring/service.yaml
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
